---
# tasks file for myloadbalancer
- name: Install the Haproxy package
  package: 
     name: "{{ package_name }}"
     state: present

- name: Change the config file of haproxy
  template:
     dest: /etc/haproxy/haproxy.cfg
     src: templates/haproxy.cfg.j2
  notify:
  - Restart the service

- name: Start the service
  service:
     name: "{{ service_name }}"
     state: started
     enabled: yes



    
   

           
          
